version: "2.0"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=4045487
        - MYSQL_DATABASE=RESTful
        - MYSQL_USER=root
        - MYSQL_PASSWORD=4045487

    php:
      image: akhmelik/php7.1
      container_name: php
      working_dir:  /var/www/Rest
      ports:
        - "8000"
      command: bin/console doctrine:database:create && bin/console doctrine:schema:create && bin/console doctrine:schema:update && bin/console server:start
      volumes:
        - .:/var/www/Rest

      links:
        - mysql